### ISSUE TITLE
cov-clear table structure

### ISSUE THREAD

**Issue by yoid2000** [diffix/coronaVirus#2]
Currently the structure of the cov-clear table pretty much matches what is exported from the typeform.com application. Each answer is a column, and the actual selected survey sentence or value is the data. Questions that have sub-questions are not listed.

It is sometimes not clear what question a given column is answering.

What would be a better format?

**Comment by yoid2000** [comment]
From Daniel:
Hey @paul , regarding table structure, I'll make some notes as they come to me.
Generally speaking, the table structure seems to come from a document store so it's not very convenient for joins. I know there's effectively  only one table, so the join can be done offline by taking the questions and then forming a query string from that, but it's a bit clunky and prevents us from showing off some of the benefits of Aircloak.
9:34
It's also hard to tell which questions and answers go together. Basically, every row is a jumble of columns, and the non-null ones are relevant, but there's no way to distinguish a question column from an answer column, or to know for example if an answer is null because it wasn't answered or because it belongs to another questions.
9:36
As a more concrete example, the column name in the survey  table (as in, the actual name of the column) encodes the column_name value from the questions table.
9:37
As a first step, it would be good to have the column names encoded as values rather than column names.
9:41
I don't know how feasible it is to encode more structure in the actual schemas but that would be very helpful. For example, break the model into questions / answers / repondents.
For example, an answers table would contain rows of answers to questions with (1) a foreign key reference to the question that was asked and (2) a ref to some data about the respondent or survey session.
9:42
I think the only way to do this, however, is to actually go through the questionnaire and map the questions and answers manually.

**Comment by yoid2000** [comment]
@dandanlen questions / answers / repondents sounds good to me. I'll play with that.

I think there is little choice but to do some manual mapping.

**Comment by dandanlen** [comment]
Can we maybe also have the old_how column mapped to numeric age columns? 
age_range_lower / age_range_upper or something like that? (we can keep the text column too of course)

**Comment by dandanlen** [comment]
One more suggestion - in the `questions` table, is it worth adding a column indicating the response type? For example, `boolean` or `tick` for tick boxes, `numeric` or `range_1_10` for the "How anxious/ill/etc. do you feel"-type questions, 'multiple_choice` for "Do you think you have had, or still have, Coronavirus?"-type question etc.

**Comment by yoid2000** [comment]
implemented survey / symptoms structure.
