### ISSUE TITLE
covid.aircloak.com/docs not publicly reachable

### ISSUE THREAD

**Issue by yoid2000** [diffix/coronaVirus#3]
The link to covid.aircloak.com/docs from https://www.kaggle.com/dlennon/aircloak-basics doesn't work.

either we should use demo.aircloak.com/docs instead, or make covid.aircloak.com publicly available.

@dandanlen @sebastian

**Comment by sebastian** [comment]
It was accessible up until recently! It worked perfectly yesterday. The link is correct. Not sure why it's broken.

**Comment by sebastian** [comment]
ok works again now.
There was a missing http -> https redirect for the corona and covid subdomains.
